import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { logger } from 'firebase-functions';
import { getFirestore } from 'firebase-admin/firestore';
import { z } from 'zod';

import { withErrorHandling } from '../utils/errorHandler';
import { enforceRateLimit } from '../utils/rateLimiter';

/**
 * Resolves an employerCode to the minimal public identity of that employer.
 *
 * Employee onboarding needs this before the user has an account, which is why
 * firestore.rules previously carried `allow list: if true` on /employers. That
 * rule returned whole documents — apiKeyHash, rfc, bankClabe, email, mlScore,
 * riskTier, llmAnalysis — to any anonymous caller running getDocs() on the
 * collection. This function is the narrow replacement: it runs with Admin SDK
 * privileges, matches on employerCode, and returns two fields.
 *
 * Unauthenticated by design (the caller has no account yet), but App Check and
 * a per-app rate limit apply so it cannot be used to enumerate codes cheaply.
 */

const LookupEmployerByCodeSchema = z.object({
  // Codes are generated by generateEmployerCode(); bound the input so this is
  // not a general-purpose query surface.
  code: z.string().trim().min(4).max(16).regex(/^[A-Za-z0-9-]+$/),
});

export type LookupEmployerByCodeInput = z.infer<typeof LookupEmployerByCodeSchema>;

export type LookupEmployerByCodeResult =
  | { found: false }
  | { found: true; employerId: string; companyName: string };

export const lookupEmployerByCode = onCall(
  // enforceAppCheck deliberately OFF (was on): the mobile app cannot attest
  // until Play Integrity is registered for mx.funpay.app (VID3-676), and this
  // endpoint is anonymous-by-design with its own defenses — zod-bounded input,
  // a fail-closed rate limit, and a two-field response. Re-enable once the
  // mobile App Check story lands; the limiter below already keys on IP for
  // unattested callers so enforcement can flip back without other changes.
  { cors: true, enforceAppCheck: false },
  async (request: {
    data: unknown;
    app?: { appId?: string };
    rawRequest?: { ip?: string };
  }): Promise<LookupEmployerByCodeResult> =>
    withErrorHandling({ functionName: 'lookupEmployerByCode' }, async () => {
      const parsed = LookupEmployerByCodeSchema.safeParse(request.data);
      if (!parsed.success) {
        throw new HttpsError('invalid-argument', 'Invalid employer code format');
      }
      const code = parsed.data.code.toUpperCase();

      // 10/min per App Check app id — enough for a user typing a code with
      // debounce, far too slow to sweep the code space. Fails CLOSED: "far too
      // slow to sweep" is only true while the limiter is answering.
      // Unattested callers (mobile, pre-App-Check) key on client IP instead of
      // sharing one global 'anon' bucket, which would let any one caller
      // exhaust the limit for everyone.
      const appCheckId = request.app?.appId ?? request.rawRequest?.ip ?? 'anon';
      await enforceRateLimit(`rl:lookupEmployerByCode:${appCheckId}`, 10, 60, {
        onUnavailable: 'closed',
        message: 'Too many lookup attempts. Please wait.',
        context: 'lookupEmployerByCode',
      });

      const db = getFirestore();
      // No `.limit(1)` here on purpose. #568 fixed the mint path (employerCode
      // is now server-minted and reserved in the `employerCodes` ledger), but
      // it did nothing about the existing book: every code minted by the old
      // client-side generator (Onboarding.tsx's `generateEmployerCode`, now
      // deleted) went straight onto the employer document with no uniqueness
      // check at all, and the ledger has no record of any of them. A
      // `.limit(1)` read cannot tell "one employer owns this code" apart from
      // "two employers collided and Firestore's default document-id ordering
      // picked one of them for you" — which is precisely how #568's squat
      // worked: the attacker re-registered until their uid sorted first. This
      // reads every match so that case is detectable instead of silently
      // resolved.
      const snap = await db.collection('employers').where('employerCode', '==', code).get();

      if (snap.empty) {
        return { found: false };
      }

      if (snap.size > 1) {
        // Fail closed with a distinct error rather than `{ found: false }`.
        // Guessing which of the two documents is the "real" one from inside
        // this function would just move the #568 bug from "attacker wins a
        // race" to "attacker wins a race and we launder it with a confident
        // `found: true`" — the caller has no way to tell a safe resolution
        // from a lucky one. `failed-precondition` (not `not-found`) so ops
        // tooling and, eventually, the client can tell "this code does not
        // exist" apart from "this code exists twice and needs a human" —
        // Onboarding.tsx currently collapses every thrown error to the same
        // "code not found" copy, so today a legitimate employee of a company
        // caught in a collision sees exactly what a typo produces: no
        // employerId is ever handed out, but they cannot self-register with
        // this code until ops resolves the duplicate (see
        // scripts/audit-duplicate-employer-codes.js). That onboarding outage
        // is the deliberate cost of not guessing.
        logger.error('lookupEmployerByCode: employerCode resolves to multiple employers', {
          employerCode: code,
          matchedEmployerIds: snap.docs.map((d) => d.id),
          service: 'functions',
        });
        throw new HttpsError(
          'failed-precondition',
          'This employer code cannot be resolved right now. Please contact your employer or support.'
        );
      }

      const doc = snap.docs[0];
      const data = doc.data() ?? {};

      // Only these two fields ever leave this function.
      return {
        found: true,
        employerId: doc.id,
        companyName: (data['companyName'] as string | undefined) ?? '',
      };
    })
);
