import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { getFirestore } from 'firebase-admin/firestore';
import { z } from 'zod';

import { withErrorHandling } from '../utils/errorHandler';
import { enforceRateLimit } from '../utils/rateLimiter';

/**
 * Resolves an employerCode to the minimal public identity of that employer.
 *
 * Employee onboarding needs this before the user has an account, which is why
 * firestore.rules previously carried `allow list: if true` on /employers. That
 * rule returned whole documents — apiKeyHash, rfc, bankClabe, email, mlScore,
 * riskTier, llmAnalysis — to any anonymous caller running getDocs() on the
 * collection. This function is the narrow replacement: it runs with Admin SDK
 * privileges, matches on employerCode, and returns two fields.
 *
 * Unauthenticated by design (the caller has no account yet), but App Check and
 * a per-app rate limit apply so it cannot be used to enumerate codes cheaply.
 */

const LookupEmployerByCodeSchema = z.object({
  // Codes are generated by generateEmployerCode(); bound the input so this is
  // not a general-purpose query surface.
  code: z.string().trim().min(4).max(16).regex(/^[A-Za-z0-9-]+$/),
});

export type LookupEmployerByCodeInput = z.infer<typeof LookupEmployerByCodeSchema>;

export type LookupEmployerByCodeResult =
  | { found: false }
  | { found: true; employerId: string; companyName: string };

export const lookupEmployerByCode = onCall(
  { cors: true, enforceAppCheck: true },
  async (request: {
    data: unknown;
    app?: { appId?: string };
  }): Promise<LookupEmployerByCodeResult> =>
    withErrorHandling({ functionName: 'lookupEmployerByCode' }, async () => {
      const parsed = LookupEmployerByCodeSchema.safeParse(request.data);
      if (!parsed.success) {
        throw new HttpsError('invalid-argument', 'Invalid employer code format');
      }
      const code = parsed.data.code.toUpperCase();

      // 10/min per App Check app id — enough for a user typing a code with
      // debounce, far too slow to sweep the code space. Fails CLOSED: "far too
      // slow to sweep" is only true while the limiter is answering.
      const appCheckId = request.app?.appId ?? 'anon';
      await enforceRateLimit(`rl:lookupEmployerByCode:${appCheckId}`, 10, 60, {
        onUnavailable: 'closed',
        message: 'Too many lookup attempts. Please wait.',
        context: 'lookupEmployerByCode',
      });

      const db = getFirestore();
      const snap = await db
        .collection('employers')
        .where('employerCode', '==', code)
        .limit(1)
        .get();

      if (snap.empty) {
        return { found: false };
      }

      const doc = snap.docs[0];
      const data = doc.data() ?? {};

      // Only these two fields ever leave this function.
      return {
        found: true,
        employerId: doc.id,
        companyName: (data['companyName'] as string | undefined) ?? '',
      };
    })
);
